kind: Deployment
apiVersion: apps/v1
metadata:
  name: frontend-deployment
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-pod
          image: dp_frontend
          imagePullPolicy: Never
          ports:
            - containerPort: 3000

---
kind: Service
apiVersion: v1
metadata:
  name: frontend-service
  namespace: default
spec:
  ports:
    - port: 3000
  selector:
    app: frontend
