kind: Deployment
apiVersion: apps/v1
metadata:
  name: backend-deployment
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: frontend-pod
          image: dp_backend
          imagePullPolicy: Never
          ports:
            - containerPort: 5000

---
kind: Service
apiVersion: v1
metadata:
  name: backend-service
  namespace: default
spec:
  ports:
    - port: 5000
  selector:
    app: backend
